Tooltip
js-tasks-ru/htmlcss-20220120_vlad-sidyukov pull request #10
Opened 2022-02-02 16:13 UTC by frontvlad

2022-02-02 16:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-02 16:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-02 22:20 UTC, GSemikozov requested changes

2022-02-02 22:20 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip__icon:hover ~ .tooltip__bubble {
здесь мы меняем состояние, гораздо удобнее было бы определить все стили длz бабл выше, а здесь только указать то чо меняем - display: block

2022-02-03 13:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-03 13:23 UTC, frontvlad commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip__icon:hover ~ .tooltip__bubble {
Исправил

2022-02-03 14:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-03 14:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-03 17:16 UTC, GSemikozov approved these changes

2022-02-03 17:16 UTC, merged