Адаптив главной страницы
js-tasks-ru/htmlcss-20220120_vlad-sidyukov pull request #14
Opened 2022-02-06 21:51 UTC by frontvlad

2022-02-06 21:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-07 21:53 UTC, GSemikozov requested changes

2022-02-07 21:53 UTC, GSemikozov commented on components/button.css
> +  .button--preview.button {
.button--preview.button -> можно просто .button--preview

2022-02-07 21:53 UTC, GSemikozov commented on components/histogram.css
> +  .histogram--preview.histogram {
.histogram--preview.histogram -> .histogram--preview

2022-02-09 08:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-09 08:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-09 16:54 UTC, GSemikozov approved these changes

2022-02-09 16:54 UTC, merged