Модалка
js-tasks-ru/htmlcss-20220120_vlad-sidyukov pull request #27
Opened 2022-03-09 15:42 UTC by frontvlad

2022-03-09 15:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-10 21:08 UTC, GSemikozov requested changes

2022-03-10 21:08 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +        <p class="modal__title">
тайтл это обычно всегда один из h1-h6 )

2022-03-10 21:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  width: 189px;
это точно необходимо? если да, то по БЭМ .modal_open. Так-то можно было бы самому окну сделать min-width при необходимости

2022-03-10 21:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  width: 189px;
хм, нет, тут точно width: 189px; будет лишним

2022-03-10 21:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  top: 15.33px;
дробные пиксели не используем

2022-03-14 16:15 UTC, frontvlad commented on 05-lection3/02-modal/index.html
> +        <p class="modal__title">
Исправил

2022-03-14 16:29 UTC, frontvlad commented on 05-lection3/02-modal/modal.css
> +  width: 189px;
Сделал max-width через родителя. modal__open я же не могу написать, так как кнопка(элемент) находится вне блока modal, поэтому сделал класс modal-open, чтобы с него можно было открывать модалку.

2022-03-14 16:30 UTC, frontvlad commented on 05-lection3/02-modal/modal.css
> +  top: 15.33px;
Вообще в верстке их не использовать? 15.5 px тоже нельзя? Это дурной тон?) Исправил.

2022-03-14 16:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-15 20:58 UTC, GSemikozov requested changes

2022-03-15 20:58 UTC, GSemikozov commented on 05-lection3/02-modal/wrapper.css
> +.wrapper__button {
слишком размытое определение для кнопки - а если у враппера будет еще 10 кнопок и у всех будут разные размеры в зависимости от контекста?))

в общем, здесь это лишнее. Лучше чтобы кнопка растягивалась по своему внутреннему содержимому по умолчанию, без необходимости задавать фиксированную ширину

2022-03-15 20:59 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  top: 15.33px;
да, лучше не использовать)

2022-03-15 21:01 UTC, GSemikozov requested changes

2022-03-15 21:01 UTC, GSemikozov commented on 05-lection3/02-modal/index.js
> +    const modalOpen = document.querySelector('.modal-open');
а в стилях я не вижу где этот класс описан. И по бЭМ все-таки .modal_open

2022-03-17 10:47 UTC, frontvlad commented on 05-lection3/02-modal/wrapper.css
> +.wrapper__button {
Исправил

2022-03-17 10:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-17 10:49 UTC, frontvlad commented on 05-lection3/02-modal/index.js
> +    const modalOpen = document.querySelector('.modal-open');
Добавил modal__open в стили ( width: auto;)

Вопрос на будущее - если мне надо как то пометить кнопку, чтобы отлавливать клики именно по ней, но стилистических изменений не требуется. Как поступать?

2022-03-20 15:00 UTC, GSemikozov commented on 05-lection3/02-modal/index.js
> +    const modalOpen = document.querySelector('.modal-open');
класс-модификатор или id, или еще делают постфикс или префикс `js` в классу кнопки чтобы пометить что это только для js

2022-03-20 15:02 UTC, GSemikozov requested changes

2022-03-20 15:02 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +    <button class="button button--primary modal__open">
modal__open - элемент блока не может существовать вне своего блока (.modal), так что этот класс вообще можно удалить. В задасче не важно как будет выглядеть кнопка вызова модалки

2022-03-20 15:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  padding: 20px;
тут точно по дизайну?)

2022-03-21 12:49 UTC, frontvlad commented on 05-lection3/02-modal/index.js
> +    const modalOpen = document.querySelector('.modal-open');
Сделал префикс js-button

2022-03-21 12:52 UTC, frontvlad commented on 05-lection3/02-modal/index.html
> +    <button class="button button--primary modal__open">
Убрал класс modal__open

2022-03-21 12:54 UTC, frontvlad commented on 05-lection3/02-modal/modal.css
> +  padding: 20px;
![Скриншот 21-03-2022 175417](https://user-images.githubusercontent.com/86065317/159264988-b5f038c9-5e78-4ad1-8543-747d71662b54.png)

2022-03-21 12:54 UTC, frontvlad commented on 05-lection3/02-modal/modal.css
> +  padding: 20px;
Вроде все выглядит как на макете)

2022-03-21 13:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-21 16:49 UTC, GSemikozov approved these changes

2022-03-21 16:49 UTC, merged