Аккордеон
js-tasks-ru/htmlcss-20220120_vlad-sidyukov pull request #7
Opened 2022-01-29 15:04 UTC by frontvlad

2022-01-29 15:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-29 15:50 UTC, GSemikozov requested changes

2022-01-29 15:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accorduon-list.css
> +.accorduon-list {
.accorduon ->> accordion )

2022-01-29 15:50 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +  <ul class="accorduon-list">
вообще,  так конечно можно. Но семантически более верно будет не использовать блочные элементы внутри li, да и вообще не использовать список. Скорее - аккордион это цельный блок, который состоит из элементов сollapsed; то есть я бы предложил избавиться от списка, то что сейчас accordion - переименовать в accordion__item и добавить марджин снизу, а все эти элементы аккордиона обернуть в div с классом accordion

2022-01-31 11:33 UTC, frontvlad commented on 03-lection1/02-accordion/accorduon-list.css
> +.accorduon-list {
Исправил

2022-01-31 11:33 UTC, frontvlad commented on 03-lection1/02-accordion/index.html
> +  <ul class="accorduon-list">
Исправил

2022-01-31 11:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-31 13:00 UTC, GSemikozov requested changes

2022-01-31 13:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  width: 730px;
все-таки не стоит жестко фиксировать ширину (на мобилке или при встраивании в другой блок сразу возникнут проблемы)

2022-01-31 13:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  margin: 0 auto;
на уровне блока марджины не задаем, контейнер был исключением.
здесь нам это может помешать - ведь не всегда нужно чтобы блок центрировался по середине

2022-01-31 13:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  color: #212429;
здесь и ниже желательно все цвета проставлять из переменных

2022-02-02 13:34 UTC, frontvlad commented on 03-lection1/02-accordion/accordion.css
> +  width: 730px;
Исправил

2022-02-02 13:34 UTC, frontvlad commented on 03-lection1/02-accordion/accordion.css
> +  margin: 0 auto;
Исправил

2022-02-02 22:16 UTC, GSemikozov approved these changes

2022-02-02 22:16 UTC, merged